name: Travelog
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  url_launcher: ^5.4.0
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  uses-material-design: true
  assets:
    - images/slider/
    - images/himages/
    - images/Mountimage/
    - images/Fallsimage/
    - images/Templesimage/
    - images/beachimages/
    
    
  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf  
          weight: 400

